// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vismy.Infrastructure.Context;

namespace Vismy.Infrastructure.Migrations
{
    [DbContext(typeof(VismyContext))]
    [Migration("20210802200604_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "9be91ad9-6f1a-4dd3-85f2-c8557b6dfd13",
                            ConcurrencyStamp = "e512cc4b-91c8-4e34-b1fc-119e9c3387b8",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "96f38acc-56f9-49a4-abcb-b91316ae7f3d",
                            ConcurrencyStamp = "5c66601f-cab0-4f52-89d3-04b259dda583",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "ed46b8f7-a782-4288-a531-bfc1d5a20df9",
                            ConcurrencyStamp = "fc5986a5-89fc-42cb-afd1-40f61e338245",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Vismy.Core.Models.Implementations.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("IconPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Vismy.Core.Models.Implementations.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PostStatusId")
                        .HasColumnType("int")
                        .HasColumnName("Post_StatusId");

                    b.Property<int>("Shared")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PostStatusId" }, "IX_Posts_Post_StatusId");

                    b.HasIndex(new[] { "UserId" }, "IX_Posts_UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Vismy.Core.Models.Implementations.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("ReportStatusId")
                        .HasColumnType("int")
                        .HasColumnName("Report_StatusId");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PostId" }, "IX_Reports_PostId");

                    b.HasIndex(new[] { "ReportStatusId" }, "IX_Reports_Report_StatusId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Vismy.Core.Models.Implementations.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Vismy.Core.Models.Implementations.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PostId" }, "IX_Video_PostId")
                        .IsUnique();

                    b.ToTable("Video");
                });

            modelBuilder.Entity("Vismy.Core.Models.Joins.PostTag", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex(new[] { "TagId" }, "IX_Post_Tag_TagId");

                    b.ToTable("Post_Tag");
                });

            modelBuilder.Entity("Vismy.Core.Models.Joins.UserPost", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserPostStatusId")
                        .HasColumnType("int")
                        .HasColumnName("User_Post_StatusId");

                    b.HasKey("UserId", "PostId");

                    b.HasIndex(new[] { "PostId" }, "IX_User_Post_PostId");

                    b.HasIndex(new[] { "UserPostStatusId" }, "IX_User_Post_User_Post_StatusId");

                    b.ToTable("User_Post");
                });

            modelBuilder.Entity("Vismy.Core.Models.Joins.UserReportAuthor", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ReportId");

                    b.HasIndex(new[] { "ReportId" }, "IX_User_Report_Author_ReportId");

                    b.ToTable("User_Report_Author");
                });

            modelBuilder.Entity("Vismy.Core.Models.Joins.UserReportModerator", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int>("UserReportModeratorStatusId")
                        .HasColumnType("int")
                        .HasColumnName("User_Report_Moderator_StatusId");

                    b.HasKey("UserId", "ReportId");

                    b.HasIndex(new[] { "ReportId" }, "IX_User_Report_Moderator_ReportId");

                    b.HasIndex(new[] { "UserReportModeratorStatusId" }, "IX_User_Report_Moderator_User_Report_Moderator_StatusId");

                    b.ToTable("User_Report_Moderator");
                });

            modelBuilder.Entity("Vismy.Core.Models.Joins.UserUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FollowerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "FollowerId");

                    b.HasIndex(new[] { "FollowerId" }, "IX_User_User_FollowerId");

                    b.ToTable("User_User");
                });

            modelBuilder.Entity("Vismy.Core.Models.Statuses.PostStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Post_Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "None",
                            Name = "None"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hidden",
                            Name = "Hidden"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Frozen",
                            Name = "Frozen"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Removed",
                            Name = "Removed"
                        });
                });

            modelBuilder.Entity("Vismy.Core.Models.Statuses.ReportStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Report_Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Violence",
                            Name = "Violence"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sexual content",
                            Name = "Sexual content"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bullying",
                            Name = "Bullying"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Drugs",
                            Name = "Drugs"
                        });
                });

            modelBuilder.Entity("Vismy.Core.Models.Statuses.UserPostStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("User_Post_Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "View shows you viewed the post before.",
                            Name = "Viewed"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Like shows you appreciate the post.",
                            Name = "Liked"
                        });
                });

            modelBuilder.Entity("Vismy.Core.Models.Statuses.UserReportModeratorStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("User_Report_Moderator_Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Approved",
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Disapproved",
                            Name = "Disapproved"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Vismy.Core.Models.Implementations.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Vismy.Core.Models.Implementations.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vismy.Core.Models.Implementations.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Vismy.Core.Models.Implementations.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vismy.Core.Models.Implementations.Post", b =>
                {
                    b.HasOne("Vismy.Core.Models.Statuses.PostStatus", "PostStatus")
                        .WithMany("Posts")
                        .HasForeignKey("PostStatusId")
                        .IsRequired();

                    b.HasOne("Vismy.Core.Models.Implementations.AspNetUser", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId");

                    b.Navigation("PostStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vismy.Core.Models.Implementations.Report", b =>
                {
                    b.HasOne("Vismy.Core.Models.Implementations.Post", "Post")
                        .WithMany("Reports")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vismy.Core.Models.Statuses.ReportStatus", "ReportStatus")
                        .WithMany("Reports")
                        .HasForeignKey("ReportStatusId")
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("ReportStatus");
                });

            modelBuilder.Entity("Vismy.Core.Models.Implementations.Video", b =>
                {
                    b.HasOne("Vismy.Core.Models.Implementations.Post", "Post")
                        .WithOne("Video")
                        .HasForeignKey("Vismy.Core.Models.Implementations.Video", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Vismy.Core.Models.Joins.PostTag", b =>
                {
                    b.HasOne("Vismy.Core.Models.Implementations.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .IsRequired();

                    b.HasOne("Vismy.Core.Models.Implementations.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Vismy.Core.Models.Joins.UserPost", b =>
                {
                    b.HasOne("Vismy.Core.Models.Implementations.Post", "Post")
                        .WithMany("UserPosts")
                        .HasForeignKey("PostId")
                        .IsRequired();

                    b.HasOne("Vismy.Core.Models.Implementations.AspNetUser", "User")
                        .WithMany("UserPosts")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.HasOne("Vismy.Core.Models.Statuses.UserPostStatus", "UserPostStatus")
                        .WithMany("UserPosts")
                        .HasForeignKey("UserPostStatusId")
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");

                    b.Navigation("UserPostStatus");
                });

            modelBuilder.Entity("Vismy.Core.Models.Joins.UserReportAuthor", b =>
                {
                    b.HasOne("Vismy.Core.Models.Implementations.Report", "Report")
                        .WithMany("UserReportAuthors")
                        .HasForeignKey("ReportId")
                        .IsRequired();

                    b.HasOne("Vismy.Core.Models.Implementations.AspNetUser", "User")
                        .WithMany("UserReportAuthors")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vismy.Core.Models.Joins.UserReportModerator", b =>
                {
                    b.HasOne("Vismy.Core.Models.Implementations.Report", "Report")
                        .WithMany("UserReportModerators")
                        .HasForeignKey("ReportId")
                        .IsRequired();

                    b.HasOne("Vismy.Core.Models.Implementations.AspNetUser", "User")
                        .WithMany("UserReportModerators")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.HasOne("Vismy.Core.Models.Statuses.UserReportModeratorStatus", "UserReportModeratorStatus")
                        .WithMany("UserReportModerators")
                        .HasForeignKey("UserReportModeratorStatusId")
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("User");

                    b.Navigation("UserReportModeratorStatus");
                });

            modelBuilder.Entity("Vismy.Core.Models.Joins.UserUser", b =>
                {
                    b.HasOne("Vismy.Core.Models.Implementations.AspNetUser", "Follower")
                        .WithMany("UserUserFollowers")
                        .HasForeignKey("FollowerId")
                        .IsRequired();

                    b.HasOne("Vismy.Core.Models.Implementations.AspNetUser", "User")
                        .WithMany("UserUserUsers")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vismy.Core.Models.Implementations.AspNetUser", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("UserPosts");

                    b.Navigation("UserReportAuthors");

                    b.Navigation("UserReportModerators");

                    b.Navigation("UserUserFollowers");

                    b.Navigation("UserUserUsers");
                });

            modelBuilder.Entity("Vismy.Core.Models.Implementations.Post", b =>
                {
                    b.Navigation("PostTags");

                    b.Navigation("Reports");

                    b.Navigation("UserPosts");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Vismy.Core.Models.Implementations.Report", b =>
                {
                    b.Navigation("UserReportAuthors");

                    b.Navigation("UserReportModerators");
                });

            modelBuilder.Entity("Vismy.Core.Models.Implementations.Tag", b =>
                {
                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("Vismy.Core.Models.Statuses.PostStatus", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Vismy.Core.Models.Statuses.ReportStatus", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Vismy.Core.Models.Statuses.UserPostStatus", b =>
                {
                    b.Navigation("UserPosts");
                });

            modelBuilder.Entity("Vismy.Core.Models.Statuses.UserReportModeratorStatus", b =>
                {
                    b.Navigation("UserReportModerators");
                });
#pragma warning restore 612, 618
        }
    }
}
